print('МЕДЕЦИНСКАЯ АНКЕТА')
petreson_name=(input('Введите свое имя: '))
family=(input('Введите свою фамилию: '))
age=(input('Введите свой возраст: '))
weight=(input('Введите свой вес: '))
print(petreson_name,family,',',age,'год',',','вес', weight)
