print('МЕДЕЦИНСКАЯ АНКЕТА')
petreson_name=(input('Введите свое имя: '))
family=(input('Введите свою фамилию: '))
age=(input('Введите свой возраст: '))
weight=(input('Введите свой вес: '))
print(petreson_name,family,',',age,'год',',','вес', weight,'- молодец, так держать!')
print(petreson_name,family,',',age,'год',',','вес', weight,'- следует заняться йогой.')
print(petreson_name,family,',',age,'год',',','вес', weight,'- необходимо обратиться к врачу!')
print(petreson_name,family,',',age,'год',',','вес', weight,'- Вам предстоит мого работы!')